### ISSUE TITLE
error install Ubuntu 16.04

### ISSUE THREAD

**Issue by indevor** [StreisandEffect/streisand#1835]
1) ssh-keygen - ok
2) sudo apt-get install git python3 python3-venv - ok
3) git clone https://github.com/StreisandEffect/streisand.git && cd streisand - ok
4) ./util/venv-dependencies.sh ./venv``

`root@advertjobsprofit1:~/streisand# ./util/venv-dependencies.sh ./venv
Found a python3 command....

This system appears to be running Ubuntu or Debian. Checking
for critical packages.

Found: build-essential
Found: python3-pip
Found: python3-openssl
Found: python3-dev
Found: python3-setuptools
Found: python3-venv
Found: python-cffi
Found: libffi-dev
Found: libssl-dev
Found: libcurl4-openssl-dev

Found all critical packages.

Collecting pip
  Using cached https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-21.0.1
Traceback (most recent call last):
  File "/root/streisand/venv/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/root/streisand/venv/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")`

5) (venv) root@advertjobsprofit1:~/streisand# source ./venv/bin/activate
6) (venv) root@advertjobsprofit1:~/streisand# ./streisand

  S T R E I S A N D

Streisand requires Ansible and it is not installed.
Please see the README Installation section on Prerequisites

**Comment by h-saber** [comment]
I've solved this issue by updating Python to 3.9 and all pip versions to 21.
But I receive a nonsense error when trying `./util/venv-dependencies.sh ./venv`
Here it is:

> Error: Command '['/root/streisand/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
> 
> 'python -m venv' failed to create directory './venv'
> 
> Note that ./venv must not exist, but its parent (.) must
> exist.
> 
> The first argument, 'new-directory', must be somewhere you can write
> to. A good place is './venv'. If it already exists, please delete the
> directory, or use a different name.
> 

This error happens while no venv directory exists there.

OS: Ubuntu 16.04

**Comment by ghost** [comment]
You need to change line 253 of /util/venv-dependencies.sh [to](https://stackoverflow.com/questions/65896334/python-pip-broken-with-sys-stderr-writeferror-exc/65896996#65896996) `our_pip_install --upgrade 'pip < 21.0'`.

**Comment by h-saber** [comment]
> You need to change line 253 of /util/venv-dependencies.sh [to](https://stackoverflow.com/questions/65896334/python-pip-broken-with-sys-stderr-writeferror-exc/65896996#65896996) `our_pip_install --upgrade 'pip < 21.0'`.

I did try this before your comment, but the scripts stops on cryptography and says you should upgrade to latest pip.

**Comment by changhefirst** [comment]
Do not upgrade python to 3.9, stay 3.5, but only upgrade the pip to 19.0.1, then comment all the 'pip_install' phases. (should two places, search all the codes.)

The codes are nearly too old.
